language: python
python:
  - "3.4"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --upgrade setuptools
  - pip install --upgrade codecov pytest pytest-cov
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - py.test --cov fispy --cov-report xml --cov-report term
  - travis-sphinx build
  #- coverage run fispy/tests/tests_fispy.py
after_success:
  - codecov
  - travis-sphinx deploy
